name: Flutter CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rewrite GitHub SSH dependencies to HTTPS
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Test
        run: flutter test
